MXC Linux BSP: linux/drivers/mxc/security/sahara2/include/adaptor.h File Reference
linux/drivers/mxc/security/sahara2/include/adaptor.h File Reference
The Adaptor component provides an interface to the device driver.
Data Structures
struct sah_dar
struct sah_register
struct scc_data
struct scc_slot_t
Typedefs
typedef struct sah_dar sah_dar_t
typedef struct sah_register sah_register_t
typedef struct scc_data scc_data_t
Functions
fsl_shw_return_t adaptor_Exec_Descriptor_Chain (sah_Head_Desc *dar, fsl_shw_uco_t *uco)
fsl_shw_return_t sah_get_results (sah_results *arg, fsl_shw_uco_t *uco)
fsl_shw_return_t sah_register (fsl_shw_uco_t *user_ctx)
fsl_shw_return_t sah_deregister (fsl_shw_uco_t *user_ctx)
Detailed Description
The Adaptor component provides an interface to the device driver.
Intended to be used by the FSL SHW API, this can also be called directly
Typedef Documentation
typedef struct sah_dar sah_dar_t
Structure passed during user ioctl() call to submit request.
typedef struct sah_register sah_register_t
Structure passed during user ioctl() call to Register a user
typedef struct scc_data scc_data_t
Structure passed during ioctl() call to request SCC operation
Function Documentation
fsl_shw_return_t adaptor_Exec_Descriptor_Chain (sah_Head_Desc * dar, fsl_shw_uco_t * uco)
Writes the Descriptor Chain to the kernel driver.
This function writes the Descriptor Chain to the kernel driver.
Parameters:
dar A pointer to a Descriptor Chain of type sah_Head_Desc
uco The user context object
Returns:
A return code of type fsl_shw_return_t.
References sah_Head_Desc::desc, FSL_RETURN_ERROR_S, FSL_RETURN_NO_RESOURCE_S, FSL_RETURN_OK_S, FSL_UCO_BLOCKING_MODE, sah_Head_Desc::result, sah_Queue_Manager_Append_Entry(), sah_Head_Desc::uco_flags, sah_Head_Desc::user_desc, and sah_Head_Desc::user_info.
fsl_shw_return_t sah_deregister (fsl_shw_uco_t * user_ctx)
Sends a request to deregister this user.
Sends a request to deregister this user
Parameters:
[in,out] user_ctx Info on user being deregistered.
Returns:
A return code of type fsl_shw_return_t.
References FSL_RETURN_OK_S, and fsl_shw_uco_t::sahara_openfd.
Referenced by fsl_shw_deregister_user().
fsl_shw_return_t sah_get_results (sah_results * arg, fsl_shw_uco_t * uco)
Sends a request to get results for this user.
Sends a request to get results for this user
Parameters:
[in,out] arg Pointer to structure to collect results
uco User's context
Returns:
A return code of type fsl_shw_return_t.
References sah_results::actual, and FSL_RETURN_OK_S.
Referenced by fsl_shw_get_results().
fsl_shw_return_t sah_register (fsl_shw_uco_t * user_ctx)
Sends a request to register this user.
Sends a request to register this user
Parameters:
[in,out] user_ctx part of the structure contains input parameters and part is filled in by the driver
Returns:
A return code of type fsl_shw_return_t.
References FSL_RETURN_OK_S, fsl_shw_uco_t::mem_util, sah_validate_uco(), and fsl_shw_uco_t::sahara_openfd.
Referenced by fsl_shw_register_user().
© Freescale Semiconductor, Inc., 2007. All rights reserved.
Freescale Confidential Proprietary
NDA Required