MXC Linux BSP: Functions for Generating References to Driver Routines
Functions for Generating References to Driver Routines
Functions
os_init_function_t OS_DEV_INIT_REF (symbol function_name)
os_shutdown_function_t OS_DEV_SHUTDOWN_REF (symbol function_name)
os_user_function_t OS_DEV_OPEN_REF (symbol function_name)
os_user_function_t OS_DEV_CLOSE_REF (symbol function_name)
os_user_function_t OS_DEV_READ_REF (symbol function_name)
os_user_function_t OS_DEV_WRITE_REF (symbol function_name)
os_user_function_t OS_DEV_IOCTL_REF (symbol function_name)
os_user_function_t OS_DEV_MMAP_REF (symbol function_name)
os_interrupt_handler_t OS_DEV_ISR_REF (symbol function_name)
Detailed Description
These functions will most likely be implemented as macros. They are a necessary part of the portable API to guarantee portability. The symbol type in here is the same symbol passed to the associated signature-generating macro.
These macros must be used whenever referring to a driver signature function, for instance when storing or passing a pointer to the function.
Function Documentation
os_user_function_t OS_DEV_CLOSE_REF (symbol function_name)
Generate a reference to an OS_DEV_CLOSE() function
Parameters:
function_name The name of the close function being referenced.
Returns:
A reference to the function
Referenced by shw_setup_user_driver_interaction().
os_init_function_t OS_DEV_INIT_REF (symbol function_name)
Generate a reference to an OS_DEV_INIT() function
Parameters:
function_name The name of the init function being referenced.
Returns:
A reference to the function
os_user_function_t OS_DEV_IOCTL_REF (symbol function_name)
Generate a reference to an OS_DEV_IOCTL() function
Parameters:
function_name The name of the ioctl function being referenced.
Returns:
A reference to the function
Referenced by rng_test_setup_user_driver_interaction(), and shw_setup_user_driver_interaction().
os_interrupt_handler_t OS_DEV_ISR_REF (symbol function_name)
Generate a reference to an OS_DEV_ISR() function
Parameters:
function_name The name of the isr being referenced.
Returns:
a reference to the function
Referenced by rng_setup_interrupt_handling().
os_user_function_t OS_DEV_MMAP_REF (symbol function_name)
Generate a reference to an OS_DEV_MMAP() function
Parameters:
function_name The name of the mmap function being referenced.
Returns:
A reference to the function
Referenced by shw_setup_user_driver_interaction().
os_user_function_t OS_DEV_OPEN_REF (symbol function_name)
Generate a reference to an OS_DEV_OPEN() function
Parameters:
function_name The name of the open function being referenced.
Returns:
A reference to the function
Referenced by shw_setup_user_driver_interaction().
os_user_function_t OS_DEV_READ_REF (symbol function_name)
Generate a reference to an OS_DEV_READ() function
Parameters:
function_name The name of the read function being referenced.
Returns:
A reference to the function
os_shutdown_function_t OS_DEV_SHUTDOWN_REF (symbol function_name)
Generate a reference to an OS_DEV_SHUTDOWN() function
Parameters:
function_name The name of the shutdown function being referenced.
Returns:
A reference to the function
os_user_function_t OS_DEV_WRITE_REF (symbol function_name)
Generate a reference to an OS_DEV_WRITE() function
Parameters:
function_name The name of the write function being referenced.
Returns:
A reference to the function
© Freescale Semiconductor, Inc., 2007. All rights reserved.
Freescale Confidential Proprietary
NDA Required