MXC Linux BSP: Functions to Return Values from Driver Signature routines
Functions to Return Values from Driver Signature routines
Functions
void os_dev_init_return (os_error_code code)
void os_dev_shutdown_return (os_error_code code)
void os_dev_isr_return (int code)
void os_dev_open_return (os_error_code code)
void os_dev_ioctl_return (os_error_code code)
void os_dev_read_return (os_error_code code)
void os_dev_write_return (os_error_code code)
void os_dev_mmap_return (os_error_code code)
void os_dev_close_return (os_error_code code)
void os_dev_task_begin (void)
void os_dev_task_return (os_error_code code)
Detailed Description
Function Documentation
void os_dev_close_return (os_error_code code)
Return from the OS_DEV_CLOSE() function
Parameters:
code An error code to report success or failure.
Referenced by OS_DEV_CLOSE().
void os_dev_init_return (os_error_code code)
Return from the OS_DEV_INIT() function
Parameters:
code An error code to report success or failure.
Referenced by OS_DEV_INIT().
void os_dev_ioctl_return (os_error_code code)
Return from the OS_DEV_IOCTL() function
Parameters:
code An error code to report success or failure.
Referenced by OS_DEV_IOCTL().
void os_dev_isr_return (int code)
Return from the OS_DEV_ISR() function
The function should verify that it really was supposed to be called, and that its device needed attention, in order to properly set the return code.
Parameters:
code non-zero if interrupt handled, zero otherwise.
Referenced by OS_DEV_ISR().
void os_dev_mmap_return (os_error_code code)
Return from the OS_DEV_MMAP() function
Parameters:
code Number of bytes written, or an error code to report failure.
void os_dev_open_return (os_error_code code)
Return from the OS_DEV_OPEN() function
Parameters:
code An error code to report success or failure.
Referenced by OS_DEV_OPEN().
void os_dev_read_return (os_error_code code)
Return from the OS_DEV_READ() function
Parameters:
code Number of bytes read, or an error code to report failure.
void os_dev_shutdown_return (os_error_code code)
Return from the OS_DEV_SHUTDOWN() function
Parameters:
code An error code to report success or failure.
Referenced by OS_DEV_SHUTDOWN().
void os_dev_task_begin (void)
Start the OS_DEV_TASK() function
In some implementations, this could be turned into a label for the os_dev_task_return() call.
For a more portable interface, should this take the sleep object as an argument???
Returns:
none
Referenced by OS_DEV_TASK().
void os_dev_task_return (os_error_code code)
Return from the OS_DEV_TASK() function
In some implementations, this could be turned into a sleep followed by a jump back to the os_dev_task_begin() call.
Parameters:
code An error code to report success or failure.
Referenced by OS_DEV_TASK().
void os_dev_write_return (os_error_code code)
Return from the OS_DEV_WRITE() function
Parameters:
code Number of bytes written, or an error code to report failure.
© Freescale Semiconductor, Inc., 2007. All rights reserved.
Freescale Confidential Proprietary
NDA Required