MXC Linux BSP: imx-test-2.6.35.3-1.1.0/test/mxc_pmic_test/pmic_testapp_light/pmic_testapp_light.c File Reference
imx-test-2.6.35.3-1.1.0/test/mxc_pmic_test/pmic_testapp_light/pmic_testapp_light.c File Reference
This is the main file of PMIC tests for Light and Backlight driver.
Functions
void enable_backlight (int fp, t_bklit_setting_param *setting)
void disable_backlight (int fp, t_bklit_setting_param *setting)
int start_fun_pattern (int fp, t_tcled_enable_param *tcled_setting, t_fun_param *fun_param)
int run_backlight_test (int fp, t_bklit_setting_param *setting)
int run_suite_backlight_test (int fp, t_bklit_setting_param *setting)
int backlight_test (int fp, t_bklit_setting_param *setting)
int fun_light_test (int fp, t_tcled_enable_param *tcled_setting, t_fun_param *fun_param)
int run_ind_light_test (int fp, t_tcled_enable_param *tcled_setting, t_tcled_ind_param *ind_param)
void ind_reset (t_tcled_ind_param *ind_param)
int ind_light_test (int fp, t_tcled_enable_param *tcled_setting, t_tcled_ind_param *ind_param)
Detailed Description
This is the main file of PMIC tests for Light and Backlight driver.
Function Documentation
int backlight_test (int fp, t_bklit_setting_param * setting)
This is the main test for the backlight.
Parameters:
fp the file pointer
setting the backlight setting
Returns:
This function returns 0 if successful.
References t_bklit_setting_param::abms, t_bklit_setting_param::abr, t_bklit_setting_param::channel, t_bklit_setting_param::current_level, t_bklit_setting_param::cycle_time, disable_backlight(), t_bklit_setting_param::duty_cycle, t_bklit_setting_param::edge_slow, t_bklit_setting_param::en_dis, t_bklit_setting_param::mode, run_backlight_test(), run_suite_backlight_test(), and t_bklit_setting_param::strobe.
void disable_backlight (int fp, t_bklit_setting_param * setting)
This function disable backlights Main, Aux and Keypad
Parameters:
tcled_setting the tcled setting
Returns:
This function returns a void
References t_bklit_setting_param::channel, t_bklit_setting_param::current_level, t_bklit_setting_param::cycle_time, t_bklit_setting_param::duty_cycle, t_bklit_setting_param::edge_slow, t_bklit_setting_param::mode, and t_bklit_setting_param::strobe.
Referenced by backlight_test().
void enable_backlight (int fp, t_bklit_setting_param * setting)
This function enable backlights Main, Aux and Keypad
Parameters:
tcled_setting the tcled setting
Returns:
This function returns a void
References t_bklit_setting_param::abms, t_bklit_setting_param::abr, t_bklit_setting_param::channel, t_bklit_setting_param::current_level, t_bklit_setting_param::cycle_time, t_bklit_setting_param::duty_cycle, t_bklit_setting_param::edge_slow, t_bklit_setting_param::en_dis, t_bklit_setting_param::mode, and t_bklit_setting_param::strobe.
int fun_light_test (int fp, t_tcled_enable_param * tcled_setting, t_fun_param * fun_param)
This is the suite test for the fun pattern. It checks that the read/write operation are coherent. Tester has to check the pattern
Parameters:
fp the file pointer
tcled_setting the tcled setting
fun_param the fun parameter
Returns:
This function returns 0 if successful.
References t_fun_param::bank, t_tcled_enable_param::bank, t_tcled_enable_param::mode, and t_fun_param::pattern.
int ind_light_test (int fp, t_tcled_enable_param * tcled_setting, t_tcled_ind_param * ind_param)
This is the suite test for the tcled ind pattern. It checks that the read/write operation are coherent.
Parameters:
fp the file pointer
tcled_setting the tcled setting
ind_param the tcled ind parameter
Returns:
This function returns 0 if successful.
References t_tcled_ind_param::bank, t_tcled_enable_param::bank, t_tcled_ind_param::channel, ind_reset(), t_tcled_ind_param::level, t_tcled_enable_param::mode, t_tcled_ind_param::pattern, and run_ind_light_test().
void ind_reset (t_tcled_ind_param * ind_param)
It reset int_param struct
Parameters:
fp the file pointer
tcled_setting the tcled setting
ind_param the tcled ind parameter
Returns:
This function returns 0 if successful.
References t_tcled_ind_param::channel, t_tcled_ind_param::half_current, t_tcled_ind_param::level, t_tcled_ind_param::pattern, t_tcled_ind_param::rampdown, t_tcled_ind_param::rampup, and t_tcled_ind_param::skip.
Referenced by ind_light_test().
int run_backlight_test (int fp, t_bklit_setting_param * setting)
This is the unit test for the backlight.
Parameters:
fp the file pointer
tcled_setting the tcled setting
fun_param the fun parameter
Returns:
This function returns 0 if successful.
References t_bklit_setting_param::abms, t_bklit_setting_param::abr, t_bklit_setting_param::channel, t_bklit_setting_param::current_level, t_bklit_setting_param::cycle_time, t_bklit_setting_param::duty_cycle, t_bklit_setting_param::edge_slow, t_bklit_setting_param::en_dis, t_bklit_setting_param::mode, and t_bklit_setting_param::strobe.
Referenced by backlight_test(), and run_suite_backlight_test().
int run_ind_light_test (int fp, t_tcled_enable_param * tcled_setting, t_tcled_ind_param * ind_param)
This is the unit test for the tcled ind pattern. It checks that the read/write operation are coherent.
Parameters:
fp the file pointer
tcled_setting the tcled setting
ind_param the tcled ind parameter
Returns:
This function returns 0 if successful.
References t_tcled_enable_param::bank, t_tcled_ind_param::bank, t_tcled_ind_param::channel, t_tcled_ind_param::level, t_tcled_ind_param::pattern, t_tcled_ind_param::rampdown, and t_tcled_ind_param::rampup.
Referenced by ind_light_test().
int run_suite_backlight_test (int fp, t_bklit_setting_param * setting)
This is the suite test for the backlight.
Parameters:
fp the file pointer
setting the backlight setting
Returns:
This function returns 0 if successful.
References t_bklit_setting_param::channel, t_bklit_setting_param::current_level, t_bklit_setting_param::cycle_time, t_bklit_setting_param::duty_cycle, t_bklit_setting_param::edge_slow, and run_backlight_test().
Referenced by backlight_test().
int start_fun_pattern (int fp, t_tcled_enable_param * tcled_setting, t_fun_param * fun_param)
This function start a specific fun pattern
Parameters:
fp the file pointer
tcled_setting the tcled setting
fun_param the fun parameter
Returns:
This function returns 0 if successful.
References t_tcled_enable_param::bank, t_fun_param::bank, and t_tcled_enable_param::mode.
© Freescale Semiconductor, Inc., 2007. All rights reserved.
Freescale Confidential Proprietary
NDA Required