MXC Linux BSP: linux/drivers/mxc/security/sahara2/sah_status_manager.c File Reference
linux/drivers/mxc/security/sahara2/sah_status_manager.c File Reference
Status Manager Function.
Defines
#define DIAG_INT_COUNT
Functions
unsigned long sah_Handle_Interrupt (sah_Execute_Status hw_status)
Variables
uint32_t done1_count
uint32_t done1busy2_count
uint32_t done1done2_count
Detailed Description
Status Manager Function.
This file contains the function which processes the Sahara status register during an interrupt.
This file does not need porting.
Define Documentation
#define DIAG_INT_COUNT
Compile-time flag to count various interrupt types.
Function Documentation
unsigned long sah_Handle_Interrupt (sah_Execute_Status hw_status)
The bulk of the interrupt handling code.
the dynameic power management flag is false when power management is not asserted and true when dpm is.
This functionx processes the status register of the Sahara, updates the state of the finished queue entry, and then tries to find more work for Sahara to do.
Parameters:
hw_status The status register of Sahara at time of interrupt. The Clear interrupt bit is already handled by this register read prior to entry into this function.
Returns:
void
References sah_Head_Desc::desc, desc_queue_lock, done1_count, done1busy2_count, done1done2_count, sah_Head_Desc::error_status, sah_Head_Desc::fault_address, sah_Head_Desc::op_status, os_lock_save_context(), os_unlock_restore_context(), sah_Find_With_State(), sah_HW_Read_DAR(), sah_HW_Read_Error_Status(), sah_HW_Read_Fault_Address(), sah_HW_Read_IDAR(), sah_HW_Read_Op_Status(), sah_HW_Write_DAR(), and sah_Head_Desc::status.
Referenced by sah_Intr_Top_Half().
Variable Documentation
uint32_t done1_count
Number of interrupts processed with Done1Done2 status. Updates to this value should only be done in interrupt processing.
Referenced by sah_Handle_Interrupt().
uint32_t done1busy2_count
Number of interrupts processed with Done1Busy2 status. Updates to this value should only be done in interrupt processing.
Referenced by sah_Handle_Interrupt().
uint32_t done1done2_count
Number of interrupts processed with Done1Done2 status. Updates to this value should only be done in interrupt processing.
Referenced by sah_Handle_Interrupt().
© Freescale Semiconductor, Inc., 2007. All rights reserved.
Freescale Confidential Proprietary
NDA Required